### ISSUE TITLE
a relevant paper and code repo!

### ISSUE THREAD

**Issue by Janghyun1230** [October2001/Awesome-KV-Cache-Compression#1]
Hello! Thanks for your work:)

Could you consider adding a following paper?
- paper: Compressed Context Memory for Online Language Model Interaction (ICLR 2024)
- GitHub: [https://github.com/snu-mllab/Context-Memory ](https://github.com/snu-mllab/Context-Memory )
- arXiv: [https://arxiv.org/abs/2312.03414 ](https://arxiv.org/abs/2312.03414 )

**Comment by October2001** [comment]
Thank you! 
Your work is very interesting, and I have added it to this GitHub repo.
